version: "3.9"

services:
  secret-printer:
    image: sokrates1989/secret-printer:DEBUG0.0.10
    secrets:
      - serverStateChecker_botToken
    environment:
      - SECRET_NAME=serverStateChecker_botToken
      - SECRET_FILE=/run/secrets/serverStateChecker_botToken
    deploy:
      mode: replicated
      replicas: 1
        

secrets:
  "serverStateChecker_botToken":
    external: true
