version: "3.9"

services:
  secret-printer:
    image: sokrates1989/secret-printer:latest
    secrets:
      - your_secret_name
    environment:
      - SECRET_NAME=your_secret_name
      - SECRET_FILE=/run/secrets/your_secret_name
    deploy:
      mode: replicated
      replicas: 1
        

secrets:
  "your_secret_name":
    external: true
